name: Render Mermaid Diagram

on:
  push:
    branches:
      - main

jobs:
  render-diagram:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Set dynamic build number
      - name: Set Build Number
        id: build_number
        run: echo "BUILD_NUMBER="${{ github.run_number }} >> $GITHUB_ENV

      # Replace placeholder in Mermaid template
      - name: Replace Build Number
        run: sed "s/{{BUILD_NUMBER}}/${{ env.BUILD_NUMBER }}/g" diagram_template.mmd > diagram.mmd

      # Install Mermaid CLI
      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      # Render Mermaid diagram
      - name: Render Diagram
        run: mmdc -i diagram.mmd -o diagram.png

      # Upload the generated diagram as an artifact
      - name: Upload Diagram Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rendered-diagram
          path: diagram.png
