name: Trigger Build

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repository Dispatch
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/sjaeger92/mermaid-demo/dispatches \
          -d '{"event_type":"build_trigger"}'
